name: On Push Test
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

  workflow_dispatch:

env:
  QASE_TESTOPS_API_TOKEN: ${{ secrets.QASE_API_TOKEN }}
  QASE_TESTOPS_PROJECT: ${{ vars.QASE_TESTOPS_PROJECT }}
  QASE_TESTOPS_RUN_COMPLETE: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get run title
        id: set_title
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          COMMIT_MESSAGE=$(git log -1 --pretty=format:%s)
          echo "QASE_TESTOPS_RUN_TITLE=qase-testng@$BRANCH_NAME: $COMMIT_MESSAGE" >> $GITHUB_ENV

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Compile project (Maven only for deps + build)
        run: mvn clean install -DskipTests

      - name: Run TestNG tests (direct Java)
        run: |
          java \
            -javaagent:$HOME/.m2/repository/org/aspectj/aspectjweaver/1.9.22/aspectjweaver-1.9.22.jar \
            -cp "target/classes:target/test-classes:libs/*" \
            com.example.base.TestRunner
